api_platform:
    title: 'Tic-Tac-Toe'
    description: 'Simple api to play Tic-Tac-Toe'
    version: '0.0.1'
    openapi:
    # The contact information for the exposed API.
        contact:
            # The identifying name of the contact person/organization.
            name: "Bruno Zanchettin"
            # The URL pointing to the contact information. MUST be in the format of a URL.
            url: "https://github.com/brurib"
            # The email address of the contact person/organization. MUST be in the format of an email address.
            email: "bruno.zanchettin@gmail.com"
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    exception_to_status:
        Symfony\Component\Serializer\Exception\ExceptionInterface: 400 # Use a raw status code (recommended)
        ApiPlatform\Core\Exception\InvalidArgumentException: !php/const Symfony\Component\HttpFoundation\Response::HTTP_BAD_REQUEST
        ApiPlatform\Core\Exception\FilterValidationException: 400
        Doctrine\ORM\OptimisticLockException: 409

        App\Exception\InvalidMoveException: 403 
